blank_issues_enabled: false

contact_links:
  - name: è–„è·è¾“å…¥æ³•å®˜ç½‘
    url: https://www.mintimate.cc/
    about: å¿«é€Ÿåˆå§‹åŒ–rimeâš¡ï¼ŒåŒæ—¶é€‚é…å¤šä¸ªå¹³å°ğŸ’»ã€‚

  - name: RIME å®šåˆ¶æ–‡æ¡£
    url: https://github.com/rime/home/wiki
    about: è¿™é‡Œæœ‰è‡ªå®šä¹‰ RIME æ–¹æ¡ˆçš„å…¨é¢æ•™ç¨‹ã€‚

  - name: å°ç‹¼æ¯«ï¼ˆWeaselï¼‰æ–‡æ¡£
    url: https://github.com/rime/weasel/wiki
    about: è¿™é‡Œæœ‰å®šåˆ¶ Weasel æ ·å¼å’Œè¡Œä¸ºçš„æŒ‡å¯¼ã€‚

  - name: é¼ é¡»ç®¡ï¼ˆSquirrelï¼‰æ–‡æ¡£
    url: https://github.com/LEOYoon-Tsaw/Rime_collections/blob/master/é¼ é¬šç®¡ä»‹é¢é…ç½®æŒ‡å—.md
    about: è¿™é‡Œæœ‰å®šåˆ¶ Squirrel æ ·å¼å’Œè¡Œä¸ºçš„å‚è€ƒèµ„æ–™ã€‚
